version: '3'
services:
  app:
    build: ./Picture
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    links:
      - app_api
      - picture_db_1
    volumes:
      - .:/Picture
    ports:
      - "3000:3000"
    environment:
      - DB_API=http://localhost:3001
  app_api:
    build: ./api/app_api
    container_name: app_api
    links:
      - picture_db_1
    volumes:
      - ./api/app_api:/webapp
    ports:
      - "3001:3000"
    command: bundle exec rails s -p 3001 -b '0.0.0.0'
  picture_db_1:
    build: ./api/picture_db_1
    container_name: picture_db_1
    volumes:
      - ./api/picture_db_1/data:/data
    environment:
      - POSTGRES_PASSWORD=12201995
      - POSTGRES_USER=postgres
      - PG_DATA=/data
